### ISSUE TITLE
Set maintainer label in images

### ISSUE THREAD

**Issue by ilveroluca** [deephealthproject/docker-libs#27]
At least some of our DeepHealth images that extend the Nvidia CUDA images report as maintainer

    "maintainer": "NVIDIA CORPORATION <cudatools@nvidia.com>",

This field needs to be reset to something sensible.

**Comment by kikkomep** [comment]
Fixed by https://github.com/deephealthproject/docker-libs/pull/29/commits/f24d6441b9b50a1434797f06dbf766011a904c4a
